language: go

go:
  - "1.13.x"
  - "1.14.x"
  - tip

services:
  - docker

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_install:
  - docker run -d --net=host --rm rabbitmq

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - go get -t -v ./...

script:
  - golangci-lint run ./...
  - go test -v -race -cpu=1,2 -tags integration -timeout 5s ./...
