language: go

go:
  - 1.9.x
  - tip

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Setup gometalinter
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - dep ensure

script:
  - gometalinter -t --vendor ./...
  - go test -v -race -cpu=1,2 -tags integration -timeout 2s ./...
